//RXCONST snippet
export const SELF_LINE_DATA_REQUEST = 'SELF_LINE_DATA_REQUEST'
export const SELF_LINE_DATA_FETCHING = 'SELF_LINE_DATA_FETCHING'
export const SELF_LINE_DATA_SUCCESS = 'SELF_LINE_DATA_SUCCESS'
export const SELF_LINE_DATA_FAILED = 'SELF_LINE_DATA_FAILED'

export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_FETCHING = 'LOGIN_FETCHING'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'

export const RELOGIN_REQUEST = 'RELOGIN_REQUEST'
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'