//RXCONST snippet
export const SELF_LINE_DATA_REQUEST = 'SELF_LINE_DATA_REQUEST'
export const SELF_LINE_DATA_FETCHING = 'SELF_LINE_DATA_FETCHING'
export const SELF_LINE_DATA_SUCCESS = 'SELF_LINE_DATA_SUCCESS'
export const SELF_LINE_DATA_FAILED = 'SELF_LINE_DATA_FAILED'